name: Docker Build and Push to Docker Hub and Hugging Face

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_HUB_REPOSITORY: eveai/eve-ai
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  HF_SPACE_ID: roshikhan3021/eve-ai

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_HUB_REPOSITORY }}:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:latest
          build-args: |
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            HEDERA_ACCOUNT_ID=${{ secrets.HEDERA_ACCOUNT_ID }}
            HEDERA_PRIVATE_KEY=${{ secrets.HEDERA_PRIVATE_KEY }}

      - name: Login to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          docker login -u _token -p $HF_TOKEN registry.hf.space

      - name: Tag and push to Hugging Face
        run: |
          docker tag ${{ env.DOCKER_HUB_REPOSITORY }}:latest registry.hf.space/${{ env.HF_SPACE_ID }}
          docker push registry.hf.space/${{ env.HF_SPACE_ID }}
