name: Docker Build and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_HUB_REPOSITORY: eveai/eve-ai # Updated with your Docker Hub username
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_HUB_REPOSITORY }}:latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:latest
          build-args: |
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            HEDERA_ACCOUNT_ID=${{ secrets.HEDERA_ACCOUNT_ID }}
            HEDERA_PRIVATE_KEY=${{ secrets.HEDERA_PRIVATE_KEY }}
